stages:
  - build_html
  - deploy
  - deploy_prod

# CI_COMMIT_REF_NAME could be a tag name, and in this case VERSION and TX_BRANCH
# cannot be set correctly, so we don't build and deploy on tags
before_script:
  - export VERSION=$(echo -n $CI_COMMIT_REF_NAME | sed 's/^lizmap\_\([0-9][0-9]*\)\_\([0-9][0-9]*\)$/\1.\2/g')
  - if [ "$VERSION" == "master" ]; then export VERSION="next"; fi
  - export TX_BRANCH="$CI_COMMIT_REF_NAME"
  - echo "VERSION=$VERSION TX_BRANCH=$TX_BRANCH"

# Build without translations, for MR
build_html_mr:
  image: ${REGISTRY_URL}/factory-ci-runner:build-doc
  only:
    - merge_requests
    - manual
  stage: build_html
  script:
    - pip list
    - make clean html SPHINXBUILD=sphinx-build SPHINXINTL=sphinx-intl
  artifacts:
    paths:
      - build/html/
    name: "lizmapdoc-$CI_COMMIT_REF_NAME"
  tags:
    - factory-plain


# Build with translations, for main branches
build_html_i18n:
  image: ${REGISTRY_URL}/factory-ci-runner:build-doc
  only:
    - master
    - lizmap_3_9
    - lizmap_3_8
  stage: build_html
  script:
    - pip list
    - ./update_from_transifex.sh -f
    - make clean html SPHINXBUILD=sphinx-build SPHINXINTL=sphinx-intl
  artifacts:
    paths:
      - build/html/
    name: "lizmapdoc-$CI_COMMIT_REF_NAME"
  tags:
    - factory-plain

push_transifex:
  image: ${REGISTRY_URL}/factory-ci-runner:build-doc
  only:
    - master
    - lizmap_3_9
    - lizmap_3_8
  stage: build_html
  script:
    - make gettext SPHINXBUILD=sphinx-build SPHINXINTL=sphinx-intl
    - tx -H $TX_API -t $TX_TOKEN push -s
  tags:
    - factory-plain

deploy_snap:
  image: ${REGISTRY_URL}/factory-ci-runner:build-doc
  only:
    - master
    - lizmap_3_9
    - lizmap_3_8
  stage: deploy
  dependencies:
    - build_html_i18n
  script:
    - rsync -e "$DEPLOYDOC_SNAP_SSH_PARAM" -P -rvvzc --delete build/html/ $DEPLOYDOC_SNAP_HOST:$DEPLOYDOC_SNAP_PATH/$VERSION
    - rsync -e "$DEPLOYDOC_SNAP_SSH_PARAM" -P -rvvzc static/ $DEPLOYDOC_SNAP_HOST:$DEPLOYDOC_SNAP_PATH/
  environment:
    name: snap
  tags:
    - factory-plain

deploy_production:
  image: ${REGISTRY_URL}/factory-ci-runner:build-doc
  only:
    - master
    - lizmap_3_9
    - lizmap_3_8
  stage: deploy_prod
  dependencies:
    - build_html_i18n
  script:
    - rsync -e "$DEPLOYDOC_PROD_SSH_PARAM" -P -rvzc --delete build/html/ $DEPLOYDOC_PROD_HOST:$DEPLOYDOC_PROD_PATH/$VERSION
    - rsync -e "$DEPLOYDOC_PROD_SSH_PARAM" -P -rvzc static/ $DEPLOYDOC_PROD_HOST:$DEPLOYDOC_PROD_PATH/
  environment:
    name: production
  when: manual
  tags:
    - factory-plain
