stages:
  - deploy

deploy_snap:
  stage: deploy
  script:
    - make clean html
    - rsync -e "$DEPLOYDOC_SNAP_SSH_PARAM" -P -rvzc --delete build/html/ $DEPLOYDOC_SNAP_HOST:$DEPLOYDOC_SNAP_PATH
  environment:
    name: snap
  only:
     - master

deploy_production:
  stage: deploy
  script:
    - make html
    - rsync -e "$DEPLOYDOC_PROD_SSH_PARAM" -P -rvzc --delete build/html/ $DEPLOYDOC_PROD_HOST:$DEPLOYDOC_PROD_PATH
  environment:
    name: production
  when: manual
  only:
     - release
     - tags
