stages:
  - build_pot
  - build_html
  - deploy

# CI_COMMIT_REF_NAME could be a tag name, and in this case VERSION and TX_BRANCH
# cannot be set correctly, so we don't build and deploy on tags
before_script:
  - export VERSION=$(echo -n $CI_COMMIT_REF_NAME | sed 's/^lizmap\_\([0-9][0-9]*\)\_\([0-9][0-9]*\)$/\1.\2/g')
  - if [ "$VERSION" == "master" ]; then export VERSION="next"; fi
  - export TX_BRANCH="$CI_COMMIT_REF_NAME"
  - echo "VERSION=$VERSION TX_BRANCH=$TX_BRANCH"

build_pot:
  only:
    - schedules
    - master
    - lizmap_3_4
  stage: build_pot
  script:
    - make gettext
  tags:
    - infrav2

build_and_publish_pot:
  except:
    - schedules
    - tags
  only:
    - master
    - lizmap_3_4
  stage: build_pot
  script:
    - make gettext
    - tx push -s --no-interactive --branch $TX_BRANCH
  tags:
    - infrav2

retrieve_po_and_build:
  only:
    - schedules
  stage: build_html
  script:
    # -f because of
    # https://github.com/transifex/transifex-client/issues/233
    # and https://github.com/transifex/transifex-client/issues/22
    - tx pull -f -l es,fi,fr,it,ja,pt,ru --branch $TX_BRANCH
    - make clean html
  artifacts:
    paths:
      - build/html/
    name: "lizmapdoc-$CI_COMMIT_REF_NAME"
  tags:
    - infrav2

build_html:
  except:
    - schedules
    - tags
  stage: build_html
  script:
    - make clean html
  artifacts:
    paths:
      - build/html/
    name: "lizmapdoc-$CI_COMMIT_REF_NAME"
  tags:
    - infrav2

deploy_snap:
  stage: deploy
  except:
    - tags
  dependencies:
    - retrieve_po_and_build
    - build_html
  script:
    - rsync -e "$DEPLOYDOC_SNAP_SSH_PARAM" -P -rvzc --delete build/html/ $DEPLOYDOC_SNAP_HOST:$DEPLOYDOC_SNAP_PATH/$VERSION
  environment:
    name: snap
  tags:
    - infrav2

deploy_production:
  only:
    - schedules
  stage: deploy
  dependencies:
    - retrieve_po_and_build
  script:
    - rsync -e "$DEPLOYDOC_PROD_SSH_PARAM" -P -rvzc --delete build/html/ $DEPLOYDOC_PROD_HOST:$DEPLOYDOC_PROD_PATH/$VERSION
  environment:
    name: production
  when: manual
  tags:
    - infrav2
