stages:
  - build_pot
  - build_html
  - deploy

before_script:
  - export VERSION=$(echo -n $CI_COMMIT_REF_NAME | sed 's/^lizmap\_\([0-9][0-9]*\)\_\([0-9][0-9]*\)$/\1.\2/g')
  - if [ "$VERSION" == "master" ]; then export VERSION="next"; fi
  - if [ "$CI_COMMIT_REF_NAME" == "master" ]; then export TX_BRANCH2="next"; else  export TX_BRANCH2="$CI_COMMIT_REF_NAME"; fi

variables:
  TX_BRANCH: master

build_pot:
  only:
    - schedules
  stage: build_pot
  script:
    - make gettext

build_and_publish_pot:
  except:
    - schedules
  stage: build_pot
  script:
    - make gettext
    - tx push -s --no-interactive --branch $TX_BRANCH

retrieve_po_and_build:
  only:
    - schedules
  stage: build_html
  script:
    - tx pull -l es,fi,fr,it,pt,ru --branch $TX_BRANCH
    - make clean html
  artifacts:
    paths:
      - build/html/
    name: "lizmapdoc_$CI_COMMIT_REF_SLUG"

build_html:
  except:
    - schedules
  stage: build_html
  script:
    - make clean html
  artifacts:
    paths:
      - build/html/
    name: "lizmapdoc_$CI_COMMIT_REF_SLUG"

deploy_snap:
  stage: deploy
  dependencies:
    - retrieve_po_and_build
    - build_html
  script:
    - echo "VERSION=$VERSION TX_BRANCH2=$TX_BRANCH2"
    - rsync -e "$DEPLOYDOC_SNAP_SSH_PARAM" -P -rvzc --delete build/html/ $DEPLOYDOC_SNAP_HOST:$DEPLOYDOC_SNAP_PATH/$(cat VERSION)/
  environment:
    name: snap

deploy_production:
  only:
    - schedules
  stage: deploy
  dependencies:
    - retrieve_po_and_build
  script:
    - rsync -e "$DEPLOYDOC_PROD_SSH_PARAM" -P -rvzc --delete build/html/ $DEPLOYDOC_PROD_HOST:$DEPLOYDOC_PROD_PATH/$(cat VERSION)/
  environment:
    name: production
  when: manual
