stages:
  - build_html
  - deploy
  - deploy_prod

# CI_COMMIT_REF_NAME could be a tag name, and in this case VERSION and TX_BRANCH
# cannot be set correctly, so we don't build and deploy on tags
before_script:
  - export VERSION=$(echo -n $CI_COMMIT_REF_NAME | sed 's/^lizmap\_\([0-9][0-9]*\)\_\([0-9][0-9]*\)$/\1.\2/g')
  - if [ "$VERSION" == "master" ]; then export VERSION="next"; fi
  - export TX_BRANCH="$CI_COMMIT_REF_NAME"
  - echo "VERSION=$VERSION TX_BRANCH=$TX_BRANCH"

# Build without translations, for MR
build_html_mr:
  only:
    - merge_requests
  stage: build_html
  script:
    - make clean html SPHINXBUILD=sphinx-build SPHINXINTL=sphinx-intl
  artifacts:
    paths:
      - build/html/
    name: "lizmapdoc-$CI_COMMIT_REF_NAME"
  tags:
    - infrav2


# Build with translations, for main branches
build_html_i18n:
  only:
    - master
    - lizmap_3_5
    - lizmap_3_6
  stage: build_html
  script:
    - ./update_from_transifex.sh
    - make clean html SPHINXBUILD=sphinx-build SPHINXINTL=sphinx-intl
  artifacts:
    paths:
      - build/html/
    name: "lizmapdoc-$CI_COMMIT_REF_NAME"
  tags:
    - infrav2

push_transifex:
  only:
    - master
    - lizmap_3_5
    - lizmap_3_6
  stage: build_html
  script:
    - make gettext SPHINXBUILD=sphinx-build SPHINXINTL=sphinx-intl
    - tx -H https://rest.api.transifex.com -t $TX_TOKEN push -s
  tags:
    - infrav2

deploy_snap:
  only:
    - master
    - lizmap_3_5
    - lizmap_3_6
  stage: deploy
  dependencies:
    - build_html_i18n
  script:
    - rsync -e "$DEPLOYDOC_SNAP_SSH_PARAM" -P -rvvzc --delete build/html/ $DEPLOYDOC_SNAP_HOST:$DEPLOYDOC_SNAP_PATH/$VERSION
  environment:
    name: snap
  tags:
    - infrav2

deploy_production:
  only:
    - master
    - lizmap_3_5
    - lizmap_3_6
  stage: deploy_prod
  dependencies:
    - build_html_i18n
  script:
    - rsync -e "$DEPLOYDOC_PROD_SSH_PARAM" -P -rvzc --delete build/html/ $DEPLOYDOC_PROD_HOST:$DEPLOYDOC_PROD_PATH/$VERSION
  environment:
    name: production
  when: manual
  tags:
    - infrav2
